<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Anki.NET</AssemblyName>
    <RootNamespace>AnkiNet</RootNamespace>

    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <PackageId>Anki.NET</PackageId>
    <PackageVersion>2.0</PackageVersion>
    <Authors>Lysrt,Clement-Jean</Authors>
    <Description>Anki.NET allows you to create Anki decks and cards from your C# application.</Description>
    <PackageTags>anki deck decks card cards</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/lysrt/Anki.NET</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lysrt/Anki.NET</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
    <NoWarn>1701;1702;AsyncFixer01</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;AsyncFixer01</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\CardsTable.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\ColTable.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\GravesTable.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\Indexes.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\NotesTable.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Infrastructure\Persistence\AnkiFile\Database\Sql\RevLogTable.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.10" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.7.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\CardsTable.sql" />
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\ColTable.sql" />
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\GravesTable.sql" />
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\Indexes.sql" />
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\NotesTable.sql" />
    <None Remove="Infrastructure\Persistence\AnkiFile\Database\Sql\RevLogTable.sql" />
  </ItemGroup>
</Project>